# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectBoard = QtWidgets.QPushButton(self.centralwidget)
        self.connectBoard.setGeometry(QtCore.QRect(220, 130, 311, 151))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.connectBoard.setFont(font)
        self.connectBoard.setObjectName("connectBoard")
        self.serialPort = QtWidgets.QComboBox(self.centralwidget)
        self.serialPort.setGeometry(QtCore.QRect(220, 70, 311, 51))
        self.serialPort.setObjectName("serialPort")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectBoard.setText(_translate("MainWindow", "Connect Board"))
        self.label.setText(_translate("MainWindow", "Port"))
